### ISSUE TITLE
No xrate function available

### ISSUE THREAD

**Issue by matejzero** [free/prometheus#1]
As said in the Grafana issue, xrate function doesn't exists when I compile your fork.

```
go get github.com/free/prometheus
git checkout xrate_v2.2.1
make build
```

Looking at the version output, it's the right version:
```
# ./prometheus --version
prometheus, version 2.2.1 (branch: xrate_v2.2.1, revision: f3e781a5af599a76edbf1c2f61a4a57ce48b371d)
```

When trying to run xrate function, I get the error `unknown function`:
```
rate(node_cpu{instance="host"}[60s])
Error executing query: parse error at char 6: unknown function with name "xrate"
```

**Comment by free** [comment]
How are you running the query? I tried by going to `localhost:9090` and running the query there.

Regardless, I just figured out how to build binaries for the full range of platforms that Prometheus supports (just do `promu crossbuild`) and I'll make a proper release with what are (at least for me) working binaries.

**Comment by matejzero** [comment]
I was running my queries the same way you did. Weird:)

Anyway, I downloaded your release and it's working now, yeey. Off to check some graphs with the new function.

Thanks for the help
