### ISSUE TITLE
Rebase xrate against release-2.7

### ISSUE THREAD

**Issue by sylr** [free/prometheus#8]
Hi!

@free Would it be possible for you to rebase your patch against prometheus/release-2.7 ?

Regards.

**Comment by sylr** [comment]
I've tried myself but there seems to be a small conflict with the subquery patch and you are far more qualified than me to resolve it.

**Comment by free** [comment]
I have merged the ~2.7.0 master into the [xrate branch](https://github.com/free/prometheus/tree/xrate), just before releasing 2.7.0-xrate. Which is also available [as a tag](https://github.com/free/prometheus/tree/2.7.0-xrate), in case you want the exact code from which the release was made.

It is not a rebase, it's a merge, but I hope that's good enough for your purposes.
