### ISSUE TITLE
v2.9.2+xrate

### ISSUE THREAD

**Issue by sylr** [free/prometheus#9]
Just wanted to let you know that I created a branch based on v2.9.2 and added your patch.

https://github.com/sylr/prometheus/tree/v2.9.2+xrate

A single patch on top of an official tag makes it easier to backport it from one branch to another without merging and potentially bringing other commits.

Cheers.

**Comment by free** [comment]
Thanks for the suggestion, applied for the `2.12.0-xrate` release. With the usual apologies for the huge delay.
